import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { SiteShell } from "@/components/site/SiteShell";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Sparkles, GraduationCap, FileEdit, Banknote, Loader2, Lock } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/ai-tools")({
  head: () => ({
    meta: [
      { title: "Free MBA AI Tools — Recommender, Essay Reviewer, Loan Predictor | CampusUpdates" },
      { name: "description", content: "Free AI-powered MBA tools: get personalized college shortlist, SOP/essay feedback, and education loan eligibility — instantly." },
    ],
  }),
  component: AIToolsPage,
});

async function runAI(action: "recommend" | "essay" | "loan", payload: Record<string, unknown>) {
  const res = await fetch("/api/ai-tools", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ action, payload }),
  });
  if (!res.ok) {
    const t = await res.text();
    throw new Error(t || "Request failed");
  }
  const data = (await res.json()) as { result: string };
  return data.result;
}

function ResultBox({ text }: { text: string }) {
  return (
    <div className="mt-6 bg-gradient-to-br from-primary-soft/40 to-accent-soft/30 border border-primary/20 rounded-2xl p-6 md:p-7">
      <div className="flex items-center gap-2 mb-4 pb-3 border-b border-primary/15">
        <div className="w-8 h-8 rounded-lg bg-primary/15 flex items-center justify-center">
          <Sparkles className="w-4 h-4 text-primary" />
        </div>
        <div>
          <div className="font-display font-bold text-sm">Your AI Analysis</div>
          <div className="text-[11px] text-ink-3">Generated by Gemini · Personalised for you</div>
        </div>
      </div>
      <article className="prose prose-sm max-w-none text-ink-2 prose-headings:font-display prose-headings:text-ink-1 prose-headings:font-bold prose-h1:text-xl prose-h2:text-lg prose-h2:mt-5 prose-h2:mb-2 prose-h3:text-base prose-h3:mt-4 prose-h3:mb-1.5 prose-p:leading-relaxed prose-p:my-2 prose-strong:text-ink-1 prose-strong:font-semibold prose-ul:my-2 prose-ul:pl-5 prose-ol:my-2 prose-ol:pl-5 prose-li:my-1 prose-li:marker:text-primary prose-a:text-primary prose-a:no-underline hover:prose-a:underline prose-table:text-[13px] prose-th:bg-primary-soft prose-th:text-ink-1 prose-th:font-semibold prose-th:p-2 prose-td:p-2 prose-td:border-t prose-code:text-primary prose-code:bg-primary-soft prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:before:content-none prose-code:after:content-none prose-blockquote:border-l-primary prose-blockquote:bg-card prose-blockquote:py-1 prose-blockquote:not-italic">
        <ReactMarkdown>{text}</ReactMarkdown>
      </article>
    </div>
  );
}

function LoginGate() {
  return (
    <div className="bg-card border-2 border-dashed border-primary/30 rounded-2xl p-10 mt-6 text-center">
      <div className="w-14 h-14 rounded-full bg-primary-soft mx-auto flex items-center justify-center mb-4">
        <Lock className="w-6 h-6 text-primary" />
      </div>
      <h3 className="font-display text-xl font-bold mb-1.5">Sign in to use AI tools — free</h3>
      <p className="text-sm text-ink-3 mb-5 max-w-md mx-auto">
        We use your profile to personalise recommendations and keep your results saved. Takes 30 seconds.
      </p>
      <div className="flex justify-center gap-2">
        <Link to="/auth">
          <Button size="lg" className="bg-primary hover:bg-primary/90 gap-2">
            <Sparkles className="w-4 h-4" /> Sign in / Create account
          </Button>
        </Link>
      </div>
    </div>
  );
}

function FormSection({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return (
    <div className="bg-card border rounded-2xl p-6 md:p-7 mt-4 shadow-sm">
      <div className="mb-5 pb-4 border-b">
        <h2 className="font-display text-xl font-bold">{title}</h2>
        <p className="text-sm text-ink-3 mt-1">{subtitle}</p>
      </div>
      {children}
    </div>
  );
}

function Field({ label, hint, required, children }: { label: string; hint?: string; required?: boolean; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="text-[13px] font-semibold text-ink-1 block">
        {label}{required && <span className="text-accent ml-0.5">*</span>}
      </label>
      {children}
      {hint && <p className="text-[11.5px] text-ink-3 leading-snug">{hint}</p>}
    </div>
  );
}

function AIToolsPage() {
  const { user } = useAuth();
  return (
    <SiteShell>
      <div className="bg-gradient-to-br from-primary/10 via-card to-accent/10 border-b">
        <div className="max-w-[1180px] mx-auto px-6 py-14">
          <span className="inline-flex items-center gap-1.5 bg-primary-soft text-primary text-xs font-bold uppercase tracking-wider px-2.5 py-1 rounded-full mb-3">
            <Sparkles className="w-3.5 h-3.5" /> AI-Powered · Free for members
          </span>
          <h1 className="font-display text-3xl md:text-4xl font-extrabold">Smart MBA tools — powered by AI</h1>
          <p className="text-ink-3 mt-2 max-w-2xl">Personalised college shortlist, expert essay review, and education-loan eligibility — instant, accurate, all in one place.</p>
        </div>
      </div>

      <div className="max-w-[980px] mx-auto px-6 py-10">
        <Tabs defaultValue="recommend">
          <TabsList className="w-full justify-start flex-wrap h-auto gap-1 bg-muted p-1">
            <TabsTrigger value="recommend" className="data-[state=active]:bg-card data-[state=active]:shadow-sm"><GraduationCap className="w-4 h-4 mr-1.5" /> College Recommender</TabsTrigger>
            <TabsTrigger value="essay" className="data-[state=active]:bg-card data-[state=active]:shadow-sm"><FileEdit className="w-4 h-4 mr-1.5" /> Essay / SOP Reviewer</TabsTrigger>
            <TabsTrigger value="loan" className="data-[state=active]:bg-card data-[state=active]:shadow-sm"><Banknote className="w-4 h-4 mr-1.5" /> Loan Eligibility</TabsTrigger>
          </TabsList>
          {!user ? (
            <LoginGate />
          ) : (
            <>
              <TabsContent value="recommend"><RecommenderForm /></TabsContent>
              <TabsContent value="essay"><EssayForm /></TabsContent>
              <TabsContent value="loan"><LoanForm /></TabsContent>
            </>
          )}
        </Tabs>
      </div>
    </SiteShell>
  );
}

const inp = "w-full px-3.5 py-2.5 border-[1.5px] border-border rounded-lg text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15 bg-card transition";

function RecommenderForm() {
  const [f, setF] = useState({ percentile: "", workEx: "", budget: "", city: "", goal: "" });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setLoading(true);
    try { setResult(await runAI("recommend", f)); }
    catch (err: any) { toast.error(err.message); }
    setLoading(false);
  };
  return (
    <FormSection title="College Recommender" subtitle="Get a personalised MBA shortlist matched to your profile, budget and goals.">
      <form onSubmit={submit} className="space-y-5">
        <div className="grid md:grid-cols-2 gap-4">
          <Field label="CAT / Entrance percentile" required hint="Your latest score (e.g. 92, 85.4)">
            <input required type="number" min={0} max={100} step={0.1} placeholder="e.g. 92" value={f.percentile} onChange={(e) => setF({ ...f, percentile: e.target.value })} className={inp} />
          </Field>
          <Field label="Work experience" hint="Years of full-time work (leave blank if fresher)">
            <input type="number" min={0} max={30} placeholder="e.g. 2" value={f.workEx} onChange={(e) => setF({ ...f, workEx: e.target.value })} className={inp} />
          </Field>
          <Field label="Budget for total fees" required hint="Maximum you can spend (e.g. ₹15L, ₹25L)">
            <input required placeholder="e.g. ₹15L" value={f.budget} onChange={(e) => setF({ ...f, budget: e.target.value })} className={inp} />
          </Field>
          <Field label="Preferred city / region" hint="Optional — leave blank for all India">
            <input placeholder="e.g. Mumbai, Bangalore, anywhere" value={f.city} onChange={(e) => setF({ ...f, city: e.target.value })} className={inp} />
          </Field>
        </div>
        <Field label="Career goal" required hint="Tell us what you want to do after MBA — be specific for better recommendations.">
          <textarea required rows={3} placeholder="e.g. Move into management consulting at MBB, or transition from engineering to product management" value={f.goal} onChange={(e) => setF({ ...f, goal: e.target.value })} className={inp} />
        </Field>
        <Button type="submit" disabled={loading} size="lg" className="w-full bg-accent hover:bg-accent/90 text-accent-foreground">
          {loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Analysing your profile…</> : <><Sparkles className="w-4 h-4 mr-2" /> Get my shortlist</>}
        </Button>
      </form>
      {result && <ResultBox text={result} />}
    </FormSection>
  );
}

function EssayForm() {
  const [essay, setEssay] = useState("");
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setLoading(true);
    try { setResult(await runAI("essay", { prompt, essay })); }
    catch (err: any) { toast.error(err.message); }
    setLoading(false);
  };
  const words = essay.split(/\s+/).filter(Boolean).length;
  return (
    <FormSection title="Essay / SOP Reviewer" subtitle="Paste your statement of purpose or admission essay — get instant feedback on structure, clarity and impact.">
      <form onSubmit={submit} className="space-y-5">
        <Field label="Essay prompt or question" hint="Optional — what was the school's prompt? Helps tailor the review.">
          <input placeholder='e.g. "Describe a leadership experience that shaped you" (optional)' value={prompt} onChange={(e) => setPrompt(e.target.value)} className={inp} />
        </Field>
        <Field label="Your essay / SOP" required hint="Paste the full text. Minimum 80 characters for a meaningful review.">
          <textarea required rows={12} placeholder="Paste your essay here…&#10;&#10;Tip: include the full draft so the reviewer can comment on flow and structure." value={essay} onChange={(e) => setEssay(e.target.value)} className={inp + " font-[450]"} />
          <div className="flex justify-between text-[11.5px] text-ink-3 mt-1">
            <span>{essay.length} characters · {words} words</span>
            <span className={words < 250 ? "text-warning" : "text-success"}>{words < 250 ? "Tip: 250–800 words works best" : "Good length ✓"}</span>
          </div>
        </Field>
        <Button type="submit" disabled={loading || essay.length < 80} size="lg" className="w-full bg-accent hover:bg-accent/90 text-accent-foreground">
          {loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Reviewing your essay…</> : <><Sparkles className="w-4 h-4 mr-2" /> Review my essay</>}
        </Button>
      </form>
      {result && <ResultBox text={result} />}
    </FormSection>
  );
}

function LoanForm() {
  const [f, setF] = useState({ income: "", coApplicant: "", fees: "", tier: "Tier 1 IIM", cibil: "750+ (Excellent)" });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setLoading(true);
    try { setResult(await runAI("loan", f)); }
    catch (err: any) { toast.error(err.message); }
    setLoading(false);
  };
  return (
    <FormSection title="Loan Eligibility Predictor" subtitle="Estimate how much education loan you can get, at what interest rate, and from which lenders.">
      <form onSubmit={submit} className="space-y-5">
        <div className="grid md:grid-cols-2 gap-4">
          <Field label="Your monthly income (₹)" required hint="Your take-home salary. Enter 0 if you're a student/fresher.">
            <input required type="number" min={0} placeholder="e.g. 60000" value={f.income} onChange={(e) => setF({ ...f, income: e.target.value })} className={inp} />
          </Field>
          <Field label="Co-applicant monthly income (₹)" hint="Usually a parent or spouse — banks need this if your income is low.">
            <input type="number" min={0} placeholder="e.g. 90000 (optional)" value={f.coApplicant} onChange={(e) => setF({ ...f, coApplicant: e.target.value })} className={inp} />
          </Field>
          <Field label="Total course fee (₹)" required hint="Tuition + hostel + living expenses for the full MBA.">
            <input required type="number" min={0} placeholder="e.g. 2500000" value={f.fees} onChange={(e) => setF({ ...f, fees: e.target.value })} className={inp} />
          </Field>
          <Field label="College tier" required hint="Top-tier colleges get better rates and higher approval chances.">
            <select value={f.tier} onChange={(e) => setF({ ...f, tier: e.target.value })} className={inp}>
              <option>Tier 1 IIM</option>
              <option>Tier 1 Private (ISB / XLRI / SP Jain)</option>
              <option>Tier 2 MBA (top private / new IIMs)</option>
              <option>Tier 3 / Online / Distance MBA</option>
            </select>
          </Field>
          <Field label="CIBIL credit score" required hint="Your or your co-applicant's credit score. Don't know it? Check on CIBIL.com (free) or pick 'No history' if you've never had a loan.">
            <select value={f.cibil} onChange={(e) => setF({ ...f, cibil: e.target.value })} className={inp}>
              <option>750+ (Excellent)</option>
              <option>700–749 (Good)</option>
              <option>650–699 (Fair)</option>
              <option>Below 650 / No credit history</option>
            </select>
          </Field>
        </div>
        <Button type="submit" disabled={loading} size="lg" className="w-full bg-accent hover:bg-accent/90 text-accent-foreground">
          {loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Calculating eligibility…</> : <><Sparkles className="w-4 h-4 mr-2" /> Check my eligibility</>}
        </Button>
      </form>
      {result && <ResultBox text={result} />}
    </FormSection>
  );
}


