/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounsellingRouteImport } from './routes/counselling'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as CollegesIdRouteImport } from './routes/colleges.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiToolsRouteImport } from './routes/api/ai-tools'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellingRoute = CounsellingRouteImport.update({
  id: '/counselling',
  path: '/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegesRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollegesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiToolsRoute = ApiAiToolsRouteImport.update({
  id: '/api/ai-tools',
  path: '/api/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/dashboard': typeof DashboardRoute
  '/loan': typeof LoanRoute
  '/news': typeof NewsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/api/ai-tools': typeof ApiAiToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/dashboard': typeof DashboardRoute
  '/loan': typeof LoanRoute
  '/news': typeof NewsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/api/ai-tools': typeof ApiAiToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/colleges': typeof CollegesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/counselling': typeof CounsellingRoute
  '/dashboard': typeof DashboardRoute
  '/loan': typeof LoanRoute
  '/news': typeof NewsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/api/ai-tools': typeof ApiAiToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/blog'
    | '/colleges'
    | '/compare'
    | '/contact'
    | '/counselling'
    | '/dashboard'
    | '/loan'
    | '/news'
    | '/tools'
    | '/api/ai-tools'
    | '/api/chat'
    | '/blog/$slug'
    | '/colleges/$id'
    | '/news/$slug'
    | '/colleges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/counselling'
    | '/dashboard'
    | '/loan'
    | '/news'
    | '/tools'
    | '/api/ai-tools'
    | '/api/chat'
    | '/blog/$slug'
    | '/colleges/$id'
    | '/news/$slug'
    | '/colleges'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tools'
    | '/auth'
    | '/blog'
    | '/colleges'
    | '/compare'
    | '/contact'
    | '/counselling'
    | '/dashboard'
    | '/loan'
    | '/news'
    | '/tools'
    | '/api/ai-tools'
    | '/api/chat'
    | '/blog/$slug'
    | '/colleges/$id'
    | '/news/$slug'
    | '/colleges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiToolsRoute: typeof AiToolsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CollegesRoute: typeof CollegesRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CounsellingRoute: typeof CounsellingRoute
  DashboardRoute: typeof DashboardRoute
  LoanRoute: typeof LoanRoute
  NewsRoute: typeof NewsRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  ApiAiToolsRoute: typeof ApiAiToolsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselling': {
      id: '/counselling'
      path: '/counselling'
      fullPath: '/counselling'
      preLoaderRoute: typeof CounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/colleges/$id': {
      id: '/colleges/$id'
      path: '/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-tools': {
      id: '/api/ai-tools'
      path: '/api/ai-tools'
      fullPath: '/api/ai-tools'
      preLoaderRoute: typeof ApiAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CollegesRouteChildren {
  CollegesIdRoute: typeof CollegesIdRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesIdRoute: CollegesIdRoute,
  CollegesIndexRoute: CollegesIndexRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiToolsRoute: AiToolsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CollegesRoute: CollegesRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CounsellingRoute: CounsellingRoute,
  DashboardRoute: DashboardRoute,
  LoanRoute: LoanRoute,
  NewsRoute: NewsRouteWithChildren,
  ToolsRoute: ToolsRoute,
  ApiAiToolsRoute: ApiAiToolsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
